/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fishingstore.view;

/**
 *
 * @author petar
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBags = new javax.swing.JButton();
        btnGroundbaits = new javax.swing.JButton();
        btnNylon = new javax.swing.JButton();
        btnReels = new javax.swing.JButton();
        btnRods = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBags.setText("Bags");
        btnBags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBagsActionPerformed(evt);
            }
        });

        btnGroundbaits.setText("Groundbaits");
        btnGroundbaits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroundbaitsActionPerformed(evt);
            }
        });

        btnNylon.setText("Nylon");
        btnNylon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNylonActionPerformed(evt);
            }
        });

        btnReels.setText("Reels");
        btnReels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReelsActionPerformed(evt);
            }
        });

        btnRods.setText("Rods");
        btnRods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRodsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRods)
                    .addComponent(btnReels)
                    .addComponent(btnNylon)
                    .addComponent(btnGroundbaits)
                    .addComponent(btnBags))
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnBags)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGroundbaits)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNylon)
                .addGap(18, 18, 18)
                .addComponent(btnReels)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRods)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagsActionPerformed
        new WindowBags().setVisible(true);
    }//GEN-LAST:event_btnBagsActionPerformed

    
    private void btnGroundbaitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroundbaitsActionPerformed
        
    }//GEN-LAST:event_btnGroundbaitsActionPerformed

    private void btnNylonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNylonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNylonActionPerformed

    private void btnReelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReelsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReelsActionPerformed

    private void btnRodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRodsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRodsActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBags;
    private javax.swing.JButton btnGroundbaits;
    private javax.swing.JButton btnNylon;
    private javax.swing.JButton btnReels;
    private javax.swing.JButton btnRods;
    // End of variables declaration//GEN-END:variables
}
